//
//  ListOrdersModels.swift
//  CleanStorePractice
//
//  Created by 조경진 on 2020/02/18.
//  Copyright (c) 2020 조경진. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

 // MARK: ListOrders 화면 안에 쓰이는 모델들을 정의
enum ListOrders
{
  // MARK: Use cases
  enum FetchOrders // 여기서의 enum들이 전부 Use case 이다.
  {
    struct Request  //API에 보내는데 필요한 Param
    {
    }
    struct Response //API로부터 response를 intercept하고 데이터를 저장
    {
      var orders: [Order]
    }
    struct ViewModel    //UI와 관련된 모든 것을 저장
    {
      struct DisplayedOrder
      {
        var id: String
        var date: String
        var email: String
        var name: String
        var total: String
      }
      var displayedOrders: [DisplayedOrder] //구조체 배열
    }
  }
}
